version: "3.8"
services:
  great-books-ui:
    build:
      context: ./Great-Books-UI
      dockerfile: Dockerfile
    ports:
      - "3000:80" # External:Internal
    networks:
      - books-net
  great-books-api:
    build:
      context: ./Books-API
      dockerfile: Dockerfile
    ports:
      - "4000:4000" # External:Internal
    networks:
      - books-net
  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    restart: always
    ports:
      - "27017:27017"
    env_file: .env
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:

networks:
  books-net:
    driver: bridge
