apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.api.name }}-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  MONGODB_CONNECTIONSTRING: {{ .Values.secret.mongoconnectionstring | b64enc | quote }}

