apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.app.name }}
  ports:
    - port: {{ .Values.app.servicePort }}
      targetPort: {{ .Values.app.containerPort }}
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.api.name }}-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.api.name }}
  ports:
    - port: {{ .Values.api.servicePort }}
      targetPort: {{ .Values.api.containerPort }}
  type: ClusterIP

