@UserName = Beanfdfds23rfdasfds
@Email = bean@gmail.com
@Password = NewPassword0!!
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZGFiMWYxZDIzOTI1NTIyZGFmYTBlZiIsIlVzZXJOYW1lIjoiQmVhbmZkZmRzMjNyZmRhc2ZkcyIsImlhdCI6MTc0MjM4NTY1MSwiZXhwIjoxNzQyOTkwNDUxfQ.H6J-RtDXuHIc2rqyUtLMnCW8OOqiz49dtyOoAeN1q8s


GET http://localhost:4000/api/

###

GET http://localhost:4000/api/auth/checkMe
Content-Type: application/json
Authorization: Bearer {{token}}

###

POST http://localhost:4000/api/getUser
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "UserName": "{{UserName}}"
}

###

POST http://localhost:4000/api/createUser
Content-Type: application/json

{
    "UserName": "{{UserName}}",
    "Email": "{{Email}}",
    "Password": "{{Password}}"
}

###

POST http://localhost:4000/api/login
Content-Type: application/json

{
    "UserName": "{{UserName}}",
    "Email": "{{Email}}",
    "Password": "{{Password}}"
}