@UserName = SamWilk
@Email = SamWilk18@gmail.com
@Password = TestPassword
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3Y2Y5MzMzZTA1MmE2MjJiYjBkNTM3MSIsIlVzZXJOYW1lIjoiU2FtV2lsayIsImlhdCI6MTc0MTY1Njg4NywiZXhwIjoxNzQyMjYxNjg3fQ.P7iKZckfhX_RfudPMRIgKo_TDfh-8qMccXt9ZNANvNo
@BookTitle = How to die in space

GET http://localhost:4000/api/

###

GET http://localhost:4000/api/getBooks:{{BookTitle}}

###

GET http://localhost:4000/api/findBookByTitle:{{BookTitle}}
