@UserName = SamWilk
@Email = SamWilk18@gmail.com
@Password = TestPassword
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZDBhYTA1NTBiNjI1YzExMWJjYWJlYiIsIlVzZXJOYW1lIjoiU2FtV2lsayIsImlhdCI6MTc0MTcyODkyOSwiZXhwIjoxNzQyMzMzNzI5fQ.gByIoROj3lcIuvbFNtmcrsvMbaZe2NKp07nzKdI7HU4
@port = 80

GET http://localhost:{{port}}/api/

###

GET http://localhost:{{port}}/api/getUser
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "UserName": "{{UserName}}"
}

###

POST http://localhost:{{port}}/api/createUser
Content-Type: application/json

{
    "UserName": "{{UserName}}",
    "Email": "{{Email}}",
    "Password": "{{Password}}"
}

###

GET http://localhost:{{port}}/api/login
Content-Type: application/json

{
    "UserName": "{{UserName}}",
    "Email": "{{Email}}",
    "Password": "{{Password}}"
}